In [1]:
import pandas as pd

In [2]:
numeric = pd.read_csv('/Users/junho/Downloads/naver_1year (1).csv')

In [3]:
numeric

,date,나스닥,코스피,코스닥,기관합계매수량,기타법인매수량,개인매수량,외국인합계매수량,종가,등락률,거래량,전일비,score1,score2,score3,변동금리,vix
0,2021-05-25,13657.17,3171.32,962.07,3.717644e+10,-3.254900e+07,-1.805565e+10,-1.908825e+10,358000.0,0.70,433413.0,1500.0,0.205740,0.477670,0.309419,0.24,18.99
1,2021-05-26,13738.00,3168.43,966.06,4.790684e+10,-3.788020e+08,-7.177119e+10,2.424315e+10,363000.0,1.40,543316.0,1500.0,0.618050,0.729894,0.629829,0.24,18.68
2,2021-05-27,13736.28,3165.51,974.08,9.866640e+09,9.310600e+07,6.036994e+10,-7.032969e+10,358000.0,-1.38,963669.0,5500.0,0.050611,0.448271,0.283389,0.24,18.29
3,2021-05-28,13748.74,3188.73,977.46,1.966990e+09,1.733319e+09,1.032580e+10,-1.402611e+10,358000.0,0.00,439112.0,-3000.0,0.290959,0.542121,0.181454,0.24,17.31
4,2021-05-29,13748.74,3188.73,977.46,1.966990e+09,1.733319e+09,1.032580e+10,-1.402611e+10,358000.0,0.00,439112.0,-3000.0,0.748295,0.880630,0.860972,0.24,17.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,2022-05-25,11434.74,2617.22,872.69,9.309665e+09,8.966875e+08,1.441310e+10,-2.461946e+10,266000.0,0.00,533307.0,1200.0,0.030344,-0.027866,0.171448,1.19,19.89
366,2022-05-26,11740.65,2612.45,871.43,-3.653108e+09,-5.994050e+07,-1.043291e+10,1.414596e+10,266000.0,0.00,541194.0,-300.0,-0.236887,-0.646228,-0.736445,1.19,19.91
367,2022-05-27,12131.13,2638.05,873.97,5.416242e+09,6.267880e+08,-1.530813e+10,9.265104e+09,270000.0,1.50,481191.0,200.0,-0.437966,-0.680426,-0.557794,1.19,18.85
368,2022-05-28,12131.13,2638.05,873.97,5.416242e+09,6.267880e+08,-1.530813e+10,9.265104e+09,270000.0,1.50,481191.0,200.0,-0.457946,-0.364431,-0.631821,1.19,18.85
369,2022-05-29,12131.13,2638.05,873.97,5.416242e+09,6.267880e+08,-1.530813e+10,9.265104e+09,270000.0,1.50,481191.0,200.0,-0.028917,0.061172,0.193104,1.19,18.85

In [6]:
df = numeric
numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      370 non-null    object
 1   나스닥       370 non-null    float64
 2   코스피       370 non-null    float64
 3   코스닥       370 non-null    float64
 4   기관합계매수량   370 non-null    float64
 5   기타법인매수량   370 non-null    float64
 6   개인매수량     370 non-null    float64
 7   외국인합계매수량  370 non-null    float64
 8   종가        370 non-null    float64
 9   등락률       370 non-null    float64
 10  거래량       370 non-null    float64
 11  전일비       370 non-null    float64
 12  score1    370 non-null    float64
 13  score2    370 non-null    float64
 14  score3    370 non-null    float64
 15  변동금리      370 non-null    float64
 16  vix       370 non-null    float64
dtypes: float64(16), object(1)
memory usage: 49.3+ KB

In [5]:
from pymongo import MongoClient
my_client = MongoClient('mongodb://localhost:27017')
mydb = my_client['final_project']
mycol = mydb['basic_numeric_naver']

In [9]:
for i in range(len(numeric)-1):
    mycol.insert_one({'date':df.loc[i,'date'],'vix':df.loc[i,'vix'],'등락률':round(df.loc[i,'등락률'],2),
                      '금리':df.loc[i,'변동금리'],'기관':df.loc[i,'기관합계매수량'],'개인':df.loc[i,'개인매수량'],
                      '외국인':df.loc[i,'외국인합계매수량'],'score1': df.loc[i,'score1'],'score2': df.loc[i,'score2'], 'score3': df.loc[i,'score3']})